package AP.group30.StardewValley.models.Items;

import AP.group30.StardewValley.models.Game;
import AP.group30.StardewValley.models.GameAssetManager;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.physics.box2d.joints.PrismaticJoint;

public enum ItemTexture {

    WOOD(GameAssetManager.assetManager.get(GameAssetManager.wood)),
    STONE(GameAssetManager.assetManager.get(GameAssetManager.stones)),

    APRICOT_TREE(GameAssetManager.assetManager.get(GameAssetManager.apricot_tree)),
    CHERRY_TREE(GameAssetManager.assetManager.get(GameAssetManager.cherry_tree)),
    BANANA_TREE(GameAssetManager.assetManager.get(GameAssetManager.banana_tree)),
    MANGO_TREE(GameAssetManager.assetManager.get(GameAssetManager.mango_tree)),
    ORANGE_TREE(GameAssetManager.assetManager.get(GameAssetManager.orange_tree)),
    PEACH_TREE(GameAssetManager.assetManager.get(GameAssetManager.peach_tree)),
    APPLE_TREE(GameAssetManager.assetManager.get(GameAssetManager.apple_tree)),
    POMEGRANATE_TREE(GameAssetManager.assetManager.get(GameAssetManager.pomegranate_tree)),
    OAK_TREE(GameAssetManager.assetManager.get(GameAssetManager.oak_tree)),
    MAPLE_TREE(GameAssetManager.assetManager.get(GameAssetManager.maple_tree)),
    PINE_TREE(GameAssetManager.assetManager.get(GameAssetManager.pine_tree)),
    MAHOGANY_TREE(GameAssetManager.assetManager.get(GameAssetManager.mahogany_tree)),
    MUSHROOM_TREE(GameAssetManager.assetManager.get(GameAssetManager.mushroom_tree)),
    TREE(GameAssetManager.assetManager.get(GameAssetManager.tree)),
    WILD_TREE(GameAssetManager.assetManager.get(GameAssetManager.wild_tree)),
    MYSTIC_TREE(GameAssetManager.assetManager.get(GameAssetManager.mystic_tree)),
    AXE(GameAssetManager.assetManager.get(GameAssetManager.axe)),
    PICKAXE(GameAssetManager.assetManager.get(GameAssetManager.pickaxe)),
    SCYTHE(GameAssetManager.assetManager.get(GameAssetManager.scythe)),
    HOE(GameAssetManager.assetManager.get(GameAssetManager.hoe)),
    WATERING_CAN(GameAssetManager.assetManager.get(GameAssetManager.wateringCan)),
    MILK_PAIL(GameAssetManager.assetManager.get(GameAssetManager.milkPail)),
    TRASH_CAN(GameAssetManager.assetManager.get(GameAssetManager.trashCan)),
    TRAINING_POLE(GameAssetManager.assetManager.get(GameAssetManager.trainingRod)),
    BAMBOO_POLE(GameAssetManager.assetManager.get(GameAssetManager.bambooPole)),
    FIBERGLASS_POLE(GameAssetManager.assetManager.get(GameAssetManager.fiberglassRod)),
    IRIDIUM_POLE(GameAssetManager.assetManager.get(GameAssetManager.iridiumRod)),

    FARMING_ICON(GameAssetManager.assetManager.get(GameAssetManager.farmingIcon)),
    FISHING_ICON(GameAssetManager.assetManager.get(GameAssetManager.fishingIcon)),
    FORAGING_ICON(GameAssetManager.assetManager.get(GameAssetManager.foragingIcon)),
    MINING_ICON(GameAssetManager.assetManager.get(GameAssetManager.miningIcon)),

    TAPPER_ICON(GameAssetManager.assetManager.get(GameAssetManager.tapperIcon)),

    FRIED_EGG(GameAssetManager.assetManager.get(GameAssetManager.friedEgg)),
    BAKED_FISH(GameAssetManager.assetManager.get(GameAssetManager.bakedFish)),
    SALAD(GameAssetManager.assetManager.get(GameAssetManager.salad)),
    OMELET(GameAssetManager.assetManager.get(GameAssetManager.omelet)),
    PUMPKIN_PIE(GameAssetManager.assetManager.get(GameAssetManager.pumpkinPie)),
    SPAGHETTI(GameAssetManager.assetManager.get(GameAssetManager.spaghetti)),
    PIZZA(GameAssetManager.assetManager.get(GameAssetManager.pizza)),
    TORTILLA(GameAssetManager.assetManager.get(GameAssetManager.tortilla)),
    MAKI_ROLL(GameAssetManager.assetManager.get(GameAssetManager.makiRoll)),
    TRIPLE_SHOT_ESPRESSO(GameAssetManager.assetManager.get(GameAssetManager.tripleShotEspresso)),
    COOKIE(GameAssetManager.assetManager.get(GameAssetManager.cookie)),
    HASH_BROWNS(GameAssetManager.assetManager.get(GameAssetManager.hashBrowns)),
    PANCAKES(GameAssetManager.assetManager.get(GameAssetManager.pancakes)),
    FRUIT_SALAD(GameAssetManager.assetManager.get(GameAssetManager.fruitSalad)),
    RED_PLATE(GameAssetManager.assetManager.get(GameAssetManager.redPlate)),
    BREAD(GameAssetManager.assetManager.get(GameAssetManager.bread)),
    SALMON_DINNER(GameAssetManager.assetManager.get(GameAssetManager.salmonDinner)),
    VEGETABLE_MEDLEY(GameAssetManager.assetManager.get(GameAssetManager.vegetableMedley)),
    FARMERS_LUNCH(GameAssetManager.assetManager.get(GameAssetManager.farmersLunch)),
    SURVIVAL_BURGER(GameAssetManager.assetManager.get(GameAssetManager.survivalBurger)),
    DISH_O_THE_SEA(GameAssetManager.assetManager.get(GameAssetManager.dishOTheSea)),
    SEAFOAM_PUDDING(GameAssetManager.assetManager.get(GameAssetManager.seafoamPudding)),
    MINERS_TREAT(GameAssetManager.assetManager.get(GameAssetManager.minersTreat)),

    DELUXE_RETAINING_SOIL(GameAssetManager.assetManager.get(GameAssetManager.deluxeRetainingSoil)),
    SPEED_GRO(GameAssetManager.assetManager.get(GameAssetManager.speedGro)),

    // *** Crops and Seeds ***
    CARROT(GameAssetManager.assetManager.get(GameAssetManager.carrot)),
    CARROT_SEEDS(GameAssetManager.assetManager.get(GameAssetManager.carrotSeeds)),
    CARROT_STAGE_1(GameAssetManager.assetManager.get(GameAssetManager.carrotStage1)),
    CARROT_STAGE_2(GameAssetManager.assetManager.get(GameAssetManager.carrotStage2)),
    CARROT_STAGE_3(GameAssetManager.assetManager.get(GameAssetManager.carrotStage3)),
    CARROT_STAGE_4(GameAssetManager.assetManager.get(GameAssetManager.carrotStage4)),
    PUMPKIN(GameAssetManager.assetManager.get(GameAssetManager.pumpkin)),
    PUMPKIN_SEEDS(GameAssetManager.assetManager.get(GameAssetManager.pumpkinSeeds)),
    PUMPKIN_STAGE_1(GameAssetManager.assetManager.get(GameAssetManager.pumpkinStage1)),
    PUMPKIN_STAGE_2(GameAssetManager.assetManager.get(GameAssetManager.pumpkinStage2)),
    PUMPKIN_STAGE_3(GameAssetManager.assetManager.get(GameAssetManager.pumpkinStage3)),
    PUMPKIN_STAGE_4(GameAssetManager.assetManager.get(GameAssetManager.pumpkinStage4)),
    PUMPKIN_STAGE_5(GameAssetManager.assetManager.get(GameAssetManager.pumpkinStage5)),
    PUMPKIN_STAGE_6(GameAssetManager.assetManager.get(GameAssetManager.pumpkinStage6)),
    GIANT_PUMPKIN(GameAssetManager.assetManager.get(GameAssetManager.giantPumpkin)),

    // crafting
    Cherry_Bomb(GameAssetManager.assetManager.get(GameAssetManager.cherry_bomb)),
    Bomb(GameAssetManager.assetManager.get(GameAssetManager.bomb)),
    Mega_Bomb(GameAssetManager.assetManager.get(GameAssetManager.mega_bomb)),
    Sprinkler(GameAssetManager.assetManager.get(GameAssetManager.sprinkler)),
    Quality_Sprinkler(GameAssetManager.assetManager.get(GameAssetManager.quality_sprinkler)),
    Iridium_Sprinkler(GameAssetManager.assetManager.get(GameAssetManager.iridium_sprinkler)),
    Charcoal_Kiln(GameAssetManager.assetManager.get(GameAssetManager.charcoal_kiln)),
    Furnace(GameAssetManager.assetManager.get(GameAssetManager.furnace)),
    Scarecrow(GameAssetManager.assetManager.get(GameAssetManager.scarecrow)),
    Deluxe_Scarecrow(GameAssetManager.assetManager.get(GameAssetManager.deluxe_scarecrow)),
    Bee_House(GameAssetManager.assetManager.get(GameAssetManager.bee_house)),
    Cheese_press(GameAssetManager.assetManager.get(GameAssetManager.cheese_press)),
    Keg(GameAssetManager.assetManager.get(GameAssetManager.keg)),
    Loom(GameAssetManager.assetManager.get(GameAssetManager.loom)),
    Mayonnaise_Machine(GameAssetManager.assetManager.get(GameAssetManager.mayonnaise_machine)),
    Oil_Maker(GameAssetManager.assetManager.get(GameAssetManager.oil_maker)),
    Preserves_Jar(GameAssetManager.assetManager.get(GameAssetManager.preserves_jar)),
    Dehydrator(GameAssetManager.assetManager.get(GameAssetManager.dehydrator)),
    Grass_Starter(GameAssetManager.assetManager.get(GameAssetManager.grass_starter)),
    Fish_Smoker(GameAssetManager.assetManager.get(GameAssetManager.fish_smoker)),
    Mystic_Tree_Seed(GameAssetManager.assetManager.get(GameAssetManager.mystic_tree_seed)),

    HONEY(GameAssetManager.assetManager.get(GameAssetManager.honey)),
    CHEESE(GameAssetManager.assetManager.get(GameAssetManager.cheese)),
    GOAT_CHEESE(GameAssetManager.assetManager.get(GameAssetManager.goatCheese)),
    BEER(GameAssetManager.assetManager.get(GameAssetManager.beer)),
    VINEGAR(GameAssetManager.assetManager.get(GameAssetManager.vinegar)),
    COFFEE(GameAssetManager.assetManager.get(GameAssetManager.coffee)),
    JUICE(GameAssetManager.assetManager.get(GameAssetManager.juice)),
    MEAD(GameAssetManager.assetManager.get(GameAssetManager.mead)),
    PALE_ALE(GameAssetManager.assetManager.get(GameAssetManager.paleAle)),
    WINE(GameAssetManager.assetManager.get(GameAssetManager.wine)),
    DRIED_MUSHROOMS(GameAssetManager.assetManager.get(GameAssetManager.driedMushrooms)),
    DRIED_FRUIT(GameAssetManager.assetManager.get(GameAssetManager.driedFruit)),
    RAISINS(GameAssetManager.assetManager.get(GameAssetManager.raisins)),
    COAL(GameAssetManager.assetManager.get(GameAssetManager.coal)),
    CLOTH(GameAssetManager.assetManager.get(GameAssetManager.cloth)),
    MAYONNAISE(GameAssetManager.assetManager.get(GameAssetManager.mayonnaise)),
    DUCK_MAYONNAISE(GameAssetManager.assetManager.get(GameAssetManager.duckMayonnaise)),
    DINOSAUR_MAYONNAISE(GameAssetManager.assetManager.get(GameAssetManager.dinosaurMayonnaise)),
    TRUFFLE_OIL(GameAssetManager.assetManager.get(GameAssetManager.truffleOil)),
    OIL(GameAssetManager.assetManager.get(GameAssetManager.oil)),
    PICKLES(GameAssetManager.assetManager.get(GameAssetManager.pickles)),
    JELLY(GameAssetManager.assetManager.get(GameAssetManager.jelly)),
    SMOKED_FISH(GameAssetManager.assetManager.get(GameAssetManager.smokedFish)),
    METAL_BAR(GameAssetManager.assetManager.get(GameAssetManager.metalBar)),

    QUARTZ(GameAssetManager.assetManager.get(GameAssetManager.quartz)),
    EARTH_CRYSTAL(GameAssetManager.assetManager.get(GameAssetManager.earth_crystal)),
    FROZEN_TEAR(GameAssetManager.assetManager.get(GameAssetManager.frozen_tear)),
    FIRE_QUARTZ(GameAssetManager.assetManager.get(GameAssetManager.fire_quartz)),
    EMERALD(GameAssetManager.assetManager.get(GameAssetManager.emerald)),
    AQUAMARINE(GameAssetManager.assetManager.get(GameAssetManager.aquamarine)),
    RUBY(GameAssetManager.assetManager.get(GameAssetManager.ruby)),
    AMETHYST(GameAssetManager.assetManager.get(GameAssetManager.amethyst)),
    TOPAZ(GameAssetManager.assetManager.get(GameAssetManager.topaz)),
    JADE(GameAssetManager.assetManager.get(GameAssetManager.jade)),
    DIAMOND(GameAssetManager.assetManager.get(GameAssetManager.diamond)),
    PRISMATIC_SHARD(GameAssetManager.assetManager.get(GameAssetManager.prismatic_shard)),
    COPPER(GameAssetManager.assetManager.get(GameAssetManager.copper)),
    IRON(GameAssetManager.assetManager.get(GameAssetManager.iron)),
    GOLD(GameAssetManager.assetManager.get(GameAssetManager.gold)),
    IRIDIUM(GameAssetManager.assetManager.get(GameAssetManager.iridium)),
    STONE2(GameAssetManager.assetManager.get(GameAssetManager.stone2)),

    HAY(GameAssetManager.assetManager.get(GameAssetManager.hay)),

    SALMON(GameAssetManager.assetManager.get(GameAssetManager.salmon)),
    SARDINE(GameAssetManager.assetManager.get(GameAssetManager.sardine)),
    SHAD(GameAssetManager.assetManager.get(GameAssetManager.shad)),
    BLUE_DISCUS(GameAssetManager.assetManager.get(GameAssetManager.blueDiscus)),
    MIDNIGHT_CARP(GameAssetManager.assetManager.get(GameAssetManager.midnightCarp)),
    SQUID(GameAssetManager.assetManager.get(GameAssetManager.squid)),
    TUNA(GameAssetManager.assetManager.get(GameAssetManager.tuna)),
    PERCH(GameAssetManager.assetManager.get(GameAssetManager.peach_tree)),
    FLOUNDER(GameAssetManager.assetManager.get(GameAssetManager.flounder)),
    LIONFISH(GameAssetManager.assetManager.get(GameAssetManager.lionfish)),
    HERRING(GameAssetManager.assetManager.get(GameAssetManager.herring)),
    GHOSTFISH(GameAssetManager.assetManager.get(GameAssetManager.ghostfish)),
    TILAPIA(GameAssetManager.assetManager.get(GameAssetManager.tilapia)),
    DORADO(GameAssetManager.assetManager.get(GameAssetManager.dorado)),
    SUNFISH(GameAssetManager.assetManager.get(GameAssetManager.sunfish)),
    RAINBOW_TROUT(GameAssetManager.assetManager.get(GameAssetManager.rainbowTrout)),
    LEGEND(GameAssetManager.assetManager.get(GameAssetManager.legend)),
    GLACIERFISH(GameAssetManager.assetManager.get(GameAssetManager.glacierfish)),
    ANGLER(GameAssetManager.assetManager.get(GameAssetManager.angler)),
    CRIMSONFISH(GameAssetManager.assetManager.get(GameAssetManager.crimsonfish));


    private final Texture texture;

    ItemTexture(Texture texture) {
        this.texture = texture;
    }

    public Texture getTexture() {
        return texture;
    }
}
